workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # for push to main
      when: always

    - if: $CI_PIPELINE_SOURCE == "merge_request_event"  # 只跑 MR
      when: always

    # 只在 MR 開到 main 時執行
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always

    # 支援手動從 UI 執行
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

    # 其他情況都不跑
    - when: never


# Define conditions for automated and manual pipelines
.ci_conditions: &ci_conditions
  rules: 
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^fix-db/ || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^style-/ || || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^fix-ci/

      when: never

    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: false  # Pipeline succeeds even if this job is not run
    
    - if: $CI_COMMIT_BRANCH == "main"  # for push to main
      when: always

    # Always allow manual triggering from web interface
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

stages:
  - test

# 空 job，保證 pipeline 被建立，且快速通過
noop:
  stage: test
  script: echo "Skipping test for fix-db/* or style-*"
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^fix-db/ || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^style-/
      when: always

# 真正的 backend test
backend-test:
  <<: *ci_conditions
  stage: test
  image: node:20.17.0
  
  before_script:
    - cd project/backend
    - npm ci
  script:
    - npm run test
  artifacts:
    paths:
      - project/backend/test-output.json
    expire_in: 1 week

# frontend 測試也一樣
frontend-test:
  <<: *ci_conditions
  stage: test
  image: node:20.17.0
  services:
    - name: mongo:8.0.8
      alias: mongo
  
  before_script:
    - cd project/frontend
    - npm ci
    - cd ../backend
    - npm ci
    - npm run dev:test &
    - cd ../frontend
    - echo "VITE_API_BASE_URL=http://localhost:3000" > .env
  script:
    - npm run test
  artifacts:
    paths:
      - project/frontend/test-output.json
    expire_in: 1 week

# Cache node_modules to speed up builds
cache:
  paths:
    - project/backend/node_modules/
    - project/frontend/node_modules/
    - ~/.npm/

