apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-counter
  namespace: moojidle
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init-counter
          image: mongo:8.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              until mongosh "mongodb://mongo:27017/moojidle" --quiet --eval "db.adminCommand('ping').ok"; do
                echo "Waiting for MongoDB..."
                sleep 2
              done

              mongosh "mongodb://mongo:27017/moojidle" --quiet --eval '
                db.counter.updateOne(
                  {},
                  {
                    $setOnInsert: {
                      announcement: 0,
                      assignments: 0,
                      assist_in: 0,
                      course: 0,
                      course_tag: 0,
                      custom_tag: 0,
                      discussion_board: 0,
                      exams: 0,
                      taken_exams: 0,
                      mailbox: 0,
                      materials: 0,
                      notification: 0,
                      notified: 0,
                      post: 0,
                      study_in: 0,
                      submitted_ass: 0,
                      teach_in: 0,
                      user: 0
                    }
                  },
                  { upsert: true }
                );
                print("counter collection is ready");
              '
