import React, { useState } from "react";
import "./AddCourseModal";

function AddCourseModal({ onClose, onAddCourse }) {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [courseId, setCourseId] = useState("");
  const [color, setColor] = useState("#4A90E2");

  // const handleAdd = () => {
  //   if (!title || !courseId) return;
  //
  //   const newCourse = {
  //     title,
  //     courseId,
  //     color,
  //     description,
  //     isTeacher: true, // 新增者就是老師
  //   };
  //
  //   onAddCourse(newCourse);
  //   onClose();
  // };
  const handleAdd = async () => { // Make the function async
    // Basic validation: Ensure title (mapped to name) is provided
    if (!title) {
      alert("請輸入課程名稱！"); // Provide user feedback
      return;
    }

    // Data to send to the backend, based on backend expectations
    const coursePayload = {
      name: title, // Map title to name
      description: description,
      syllabus: "", // Send empty string as syllabus is missing in the form
      // course_id is generated by backend
      // color is not used by backend
    };

    try {
      const response = await fetch('/course/create', { // Use the correct API endpoint
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(coursePayload),
      });

      if (!response.ok) {
        // Handle HTTP errors (e.g., 400, 500)
        const errorData = await response.json();
        throw new Error(errorData.message || `HTTP error! status: ${response.status}`);
      }

      // Get the newly created course data from the response
      const newCourse = await response.json();

      // Call the onAddCourse prop (likely to update UI state) with the actual course data from backend
      onAddCourse(newCourse);
      onClose(); // Close the modal on success

    } catch (error) {
      console.error("新增課程失敗:", error);
      alert(`新增課程失敗: ${error.message}`); // Show error to user
    }
  };

  return (
    <div className="modal-backdrop">
      <div className="modal">
        <h3>新增課程</h3>
        <input
          placeholder="課程代碼 (courseId)"
          value={courseId}
          onChange={(e) => setCourseId(e.target.value)}
        />
        <input
          placeholder="課程名稱"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
        />
        <textarea
          placeholder="課程描述"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
        />
        <input
          type="color"
          value={color}
          onChange={(e) => setColor(e.target.value)}
        />
        <div className="modal-btn-group">
          <button onClick={handleAdd}>確定新增</button>
          <button onClick={onClose}>取消</button>
        </div>
      </div>
    </div>
  );
}

export default AddCourseModal;
